### ISSUE TITLE
Calculator does not have multiply and division

### ISSUE THREAD

**Issue by Oceanestars** [Oceanestars/TestPullRequest#1]
Python[ file](https://github.com/Oceanestars/TestPullRequest/blob/main/Calculator.py)
What should I do?

Answer below

**Comment by frameDoubt** [comment]
I read somewhere that python uses white space in code, like brackets in other languages. So I suggest looking at the spacing on line 12 and 15, also I don't know much about python. Just trying to be helpful. On line 12 and 15 it looks like you pressed tab one too many times.

**Comment by Oceanestars** [comment]
Great suggestion! Thank you! (Also, just in case you were wondering, this repo is more or less a place for people to freely test the pull request and issue feature of GitHub)(So I welcome any suggestion on any of the files. If people want to suggest other ways  to do something simple that is also welcome :) )
